# Generated by Django 3.0.7 on 2021-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_desc', models.CharField(max_length=2000)),
                ('post_head1', models.CharField(max_length=200)),
                ('post_desc1', models.CharField(max_length=2000)),
                ('post_head2', models.CharField(max_length=200)),
                ('post_desc2', models.CharField(max_length=2000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
