# Generated by Django 3.0.7 on 2021-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id1', models.AutoField(primary_key=True, serialize=False)),
                ('post1', models.CharField(max_length=400)),
                ('ts', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='blog/images')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='auth_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
