# Generated by Django 3.0.7 on 2021-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercomm',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='anonymous', max_length=40)),
                ('desc', models.CharField(default='', max_length=3000)),
                ('ts1', models.DateField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userreply',
            fields=[
                ('user_id1', models.AutoField(primary_key=True, serialize=False)),
                ('user_name1', models.CharField(default='anonymous', max_length=40)),
                ('desc1', models.CharField(default='', max_length=3000)),
                ('ts2', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
