# Generated by Django 3.0.7 on 2021-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userreply_comm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_comm_id', models.IntegerField(default=0)),
                ('like_user_id', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercomm',
            name='like',
        ),
    ]
