# Generated by Django 3.0.7 on 2021-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210131_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomm',
            name='blog_id1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlike',
            name='blog_id3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreply',
            name='blog_id2',
            field=models.IntegerField(default=0),
        ),
    ]
