# Generated by Django 3.1.6 on 2021-02-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210208_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomm',
            name='user_name',
            field=models.CharField(default='anonymous', max_length=40),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='like_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='user_name1',
            field=models.CharField(default='anonymous', max_length=40),
        ),
    ]
