# Generated by Django 3.1.6 on 2021-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210208_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('userlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('userlist_blog_id', models.IntegerField(default=0)),
                ('userlist_comm_id', models.IntegerField(default=0)),
                ('userlist_like_id', models.IntegerField(default=0)),
                ('userlist_user', models.CharField(max_length=30)),
            ],
        ),
    ]
