# Generated by Django 3.1.6 on 2021-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='conatct',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_name', models.CharField(max_length=30)),
                ('con_email', models.CharField(max_length=80)),
                ('con_phone', models.CharField(max_length=15)),
                ('con_desc', models.CharField(max_length=800)),
            ],
        ),
    ]
