# Generated by Django 3.0.7 on 2021-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.IntegerField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
